version: '3'

services:
    ktp-db:
        image: mariadb:10.3
        ports: 
            - 3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=supremokr
            - MYSQL_DATABASE=ktp_db
        networks: 
            - ktp-network
        restart: unless-stopped
    
    ktp-app:
        working_dir: /app
        build: .
        ports:
            - 8081:8080
        networks: 
            - ktp-network
        restart: unless-stopped
        depends_on: 
            - ktp-db
    
networks: 
    ktp-network:
        driver: bridge
