// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"mariadb/internal/models"
)

// Input body for update and input Ktp
type KtpBody struct {
	Nik          string `json:"nik"`
	Nama         string `json:"nama"`
	JenisKelamin string `json:"jenis_kelamin"`
	TanggalLahir string `json:"tanggal_lahir"`
	Alamat       string `json:"alamat"`
	Agama        string `json:"agama"`
}

// Default input pagination
type Pagination struct {
	First  int64  `json:"first"`
	Offset int64  `json:"offset"`
	After  *int64 `json:"after"`
}

// Object that is being paginated
type PaginationEdgeKtp struct {
	Node   *models.Ktp `json:"node"`
	Cursor int64       `json:"cursor"`
}

// Information about pagination
type PaginationInfo struct {
	EndCursor   int64 `json:"endCursor"`
	HasNextPage bool  `json:"hasNextPage"`
}

// Result when querying list using graphql
type PaginationResultKtp struct {
	TotalCount int64                `json:"totalCount"`
	Edges      []*PaginationEdgeKtp `json:"edges"`
	PageInfo   *PaginationInfo      `json:"pageInfo"`
}
