// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Input body for update and input Ktp
type KtpBody struct {
	Nik          string `json:"nik"`
	Nama         string `json:"nama"`
	JenisKelamin string `json:"jenis_kelamin"`
	TanggalLahir string `json:"tanggal_lahir"`
	Alamat       string `json:"alamat"`
	Agama        string `json:"agama"`
}
